### PR TITLE
Changing Error visibility

### PR DESCRIPTION
**Pull request by guilhermeRey**
Changing model class Error visibility modifier to public, so we can get error details when doing exception handling.

---
This change is [Reviewable](https://reviewable.io/reviews/moip/moip-sdk-java/17)

### CODE REVIEW

**Comment by somentelucas** [comment]
Hey guys, @guilhermeRey @gputrick can you tell me what is the use case to access the class `Error` instead of the `ErrorBuilder` (this one is already public)?

**Comment by gputrick** [comment]
> Hey guys, @guilhermeRey @gputrick can you tell me what is the use case to access the class `Error` instead of the `ErrorBuilder` (this one is already public)?

I believe the 'ErrorBuilder' is for build an error object, and not to get the error message.
The use case will be something like this:
```java
catch(ValidationException e) 
      {
	e.getErrors().getErrors().forEach(
           (error) -> System.err.println(error.getDescription()));
	throw e;
      }
```
This is useful to see the error details in the console or even show the error message on front-end.

**Comment by somentelucas** [comment]
@guilhermeRey @gputrick thanks a lot for contributing! The release is made, new version is `1.1.0`. 😉

**Comment by guilhermeRey** [comment]
Thank you!

**Pull request merged**
